In [1]:
import torch
import numpy as np
import matplotlib.pyplot as plt


import csv
import torch.nn as nn
import torch.nn.functional as F


In [2]:
filename = "../iris.data"
data = []
answer = []
with open(filename,"r") as f:
    reader = csv.reader(f)
    for row in reader:
        if len(row)!=0:
            if row[4]=='Iris-setosa':
                ans=[1,0,0]
            elif row[4] ==  'Iris-versicolor':
                ans = [0,1,0]
            elif row[4] ==  'Iris-virginica':
                ans = [0,0,1]
            data.append(row[:-1])
            answer.append(ans)
        
            

In [3]:
d1 = data[:50]
d2 = data[50:100]
d3 = data[100:150]
a1 = answer[:50]
a2 = answer[50:100]
a3 = answer[100:150]
train = []
check = []
train_a = []
check_a = []
for n in range(50):
    if n<33:
        train.append(d1[n])
        train.append(d2[n])
        train.append(d3[n])
        train_a.append(a1[n])
        train_a.append(a2[n])
        train_a.append(a3[n])
    else:
        check.append(d1[n])
        check.append(d2[n])
        check.append(d3[n])
        check_a.append(a1[n])
        check_a.append(a2[n])
        check_a.append(a3[n])


In [4]:
train = np.array(train,dtype=np.float32)
train_a = np.array(train_a,dtype=np.float32)
check = np.array(check,dtype=np.float32)
check_a = np.array(check_a,dtype=np.float32)

In [5]:
def dataToTensor(x):
    data = torch.from_numpy(x)
    return data

In [55]:
class Net(nn.Module):
    def __init__(self):
        super(Net,self).__init__()
        self.fc1 = nn.Linear(1,5)
        self.fc2 = nn.Linear(5,4)
        self.fc3 = nn.Linear(4,2)
        self.fc4 = nn.Linear(4,3)
        self.fc5 = nn.Linear(2,1)
        self.relu = nn.Sigmoid()
    
    def forward(self,x):
        x = self.relu(self.fc1(x))
        x = self.relu(self.fc2(x))
        x = self.relu(self.fc3(x))
        x = self.relu(self.fc4(x.T).T)
        x = self.relu(self.fc5(x))
        return x.reshape(3,1)
    

In [56]:
model = Net()
criterion = nn.MSELoss()

optimizer = torch.optim.Adam(model.parameters(),lr=0.01)

In [64]:
for epoch in range(20):
    for n in range(len(train)):
        data = dataToTensor(train[n]).reshape(4,1)
        ans = dataToTensor(train_a[n]).reshape(3,1)
        output = model(data)
#         print(output,"\n",ans,"\n","*****"*3)
#         print(output.size(),ans.size())
        loss = criterion(output,ans)
        
        print("Epoch: %i\tLoss: %f" %(epoch,loss),end="\r")
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
    print("\n")

Epoch: 0	Loss: 0.000030

Epoch: 1	Loss: 0.000027

Epoch: 2	Loss: 0.000024

Epoch: 3	Loss: 0.000021

Epoch: 4	Loss: 0.000019

Epoch: 5	Loss: 0.000017

Epoch: 6	Loss: 0.000016

Epoch: 7	Loss: 0.000015

Epoch: 8	Loss: 0.000013

Epoch: 9	Loss: 0.000012

Epoch: 10	Loss: 0.000011

Epoch: 11	Loss: 0.000011

Epoch: 12	Loss: 0.000010

Epoch: 13	Loss: 0.000010

Epoch: 14	Loss: 0.000009

Epoch: 15	Loss: 0.000009

Epoch: 16	Loss: 0.000009

Epoch: 17	Loss: 0.000009

Epoch: 18	Loss: 0.000009

Epoch: 19	Loss: 0.000009



In [85]:
correct = 0
total = len(check)
checkList = []

In [86]:
for n in range(total):
    checkList = []
    data = dataToTensor(check[n]).reshape(4,1)
    ans = dataToTensor(check_a[n]).float().reshape(1,3)
    output = model(data)
#     print(output)
#     print(ans)
    for i in output.data:
        
        if i.item() == torch.max(output.data):
            checkList.append(1)
        else:
            checkList.append(0)
        
    checkTensor = torch.tensor(checkList).reshape(1,3)
    if torch.all(torch.eq(checkTensor,ans)):
        correct+=1
    proc = (correct/total)*100
print("Total predict is: %f %%" %proc)
print("correct is: %f" %correct)

Total predict is: 96.078431 %
correct is: 49.000000


In [30]:
r

tensor([0.3371])
tensor([0.3371])
tensor([0.])


In [29]:
output

tensor([[0.3371],
        [0.3371],
        [0.0000]])